### PR TITLE
shrinked logo and some new archived artifacts from tech peers

### PR DESCRIPTION
**Pull request by immartian**
- We have to find a designer to refine the logo to make it compatible with the whole theme/dimensions,  temporarily I trimmed it to fit better visually(yet to see)
- Some new artifacts just arrived upon further merging into pages @maklokgai is preparing

### CODE REVIEW

**Comment by maklokgai** [comment]
Thanks for updating the logo.
The black & yellow color scheme may not be what the ultimate scheme we want for the website? If so, we can still change the color a bit.
Another thing, in the current logo, the "S" with a helmet is from a designer whom I haven't contacted yet. If we are to use it publicly, I will contact him and seek his authorization.

**Comment by immartian** [comment]
> in the current logo, the "S" with a helmet is from a designer whom I haven't contacted yet
we are still under the radar and free to play around with new ideas. we are asking some international designers but best to find someone locally, any ideas?

**Comment by gulprun** [comment]
Ok, I will regard it as approval, @maklokgai , as we want to test the effect of the downsized logo, if you don't disagree.

**Comment by maklokgai** [comment]
> 

I am not entirely sure how to use this review/approval function in Github...sorry
I do not personally know any designers locally in HK, and there may be a trust issue if I am to engage them in projects of similar nature.

We can surely test the logo out. Until we engage a designer, we can test the existing options

**Comment by gulprun** [comment]
> I am not entirely sure how to use this review/approval function in Github

Ha, it's actually very easy to check the files changed and click approve with comments there. Or simply uttering a word, "good", blah, blah, no pressure. 
image

**Pull request merged**
